version: '3.8'
services:
  api:
    build: .
    container_name: nextfullstack
    ports:
      - '4001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dockernet

networks:
  dockernet:
    external: true
